import { StyleSheet } from "react-native";
const CadastroStyle = StyleSheet.create({
  centralizarFlexi: {
    flex: 1,
    width: "100%",
    height: "100%",
    flexDirection: "column",
    justifyContent: "center",
  },
  ImagemDeFundo: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
    alignItems: "center",
  },
  TituloLogin: {
    width: "100%",
    color: "white",
    fontWeight: "bold",
    position: "absolute",
    fontSize: 90,
    top: "15%",
    textAlign: "center",
  },
  input: {
    backgroundColor: "white",
    width: "100%",
    height: "100%",
    position: "absolute",
    textAlign: "center",
    borderRadius: 10,
    top: "16%",
    margin: "5%",
  },
  iconDentroDoInput: {
    position: "absolute",
    width: 30,
    height: 30,
    left: "2%",
    top: "70%",
  },
  botoes: {
    width: "50%",
    height: "9%",
    position: "relative",
    backgroundColor: "#9558F5",
    top: "15%",
    borderRadius: 15,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: "5%",
  },
  div: {
    position: "absolute",
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  TextoDentroDoBotao: {
    position: "absolute",
    width: "100%",
    color: "white",
    fontSize: 25,
    textAlign: "center",
    fontWeight: "bold",
  },
});
export default CadastroStyle;
