import { StyleSheet } from "react-native";
const CompraStyles = StyleSheet.create({
  body: {
    position: "absolute",
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
  },
  Modal: {
    width: "80%",
    height: "60%",
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    overflow: "hidden",
    borderRadius: 30,
  },
  capa: {
    position: "absolute",
    left: "5%",
    top: "10%",
    width: "40%",
    height: "40%",
  },
  CaixadeTexto: {
    position: "absolute",
    right: "5%",
    top: "10%",
    width: "45%",
    height: "40%",
    backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  Titulo: {
    position: "absolute",
    top: "2%",
    width: "100%",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 18,
  },
  Texto: {
    width: "100%",
    fontSize: 13,
    textAlign: "center",
  },
  BotaoDeComprar: {
    position: "absolute",
    bottom: "0%",
    width: "60%",
    height: "15%",
    backgroundColor: "green",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    marginBottom: "10%",
  },
  posicionarElementosNoBotaoDeComprar: {
    position: "absolute",
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  TextoDentroDoBotaoDecomprar: {
    width: "100%",
    fontSize: 25,
    color: "white",
    textAlign: "center",
    fontWeight: "bold",
    marginLeft: "5%",
  },
});
export default CompraStyles;
