import { StyleSheet } from "react-native";

const TelaDoLivroStyles = StyleSheet.create({
  fundo: {
    width: "100%",
    height: "100%",
    position: "absolute",
    opacity: 0.9,
    display: "flex",
    alignItems: "center",
  },
  caixaDeinformacao: {
    position: "absolute",
    width: "90%",
    height: "40%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    marginTop: "6%",
    borderRadius: 10,
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    paddingLeft: "5%",
  },
  caixaDaCapa: {
    position: "absolute",
    left: "5%",
    top: "10%",
    width: 145,
    height: 260,
    elevation: 5,
  },
  capa: {
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  containerDeTexto: {
    position: "absolute",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 230,
    height: 290,
    right: "2%",
    top: "5%",
    borderRadius: 5,
  },
  CaixaDeTexto: {
    width: "70%",
    height: "70%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "column",
  },
  imagemAntiga: {
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  nome: {
    width: "100%",
    color: "black",
    textAlign: "center",
    fontSize: 20,
    fontFamily: "CedarvilleCursive_400Regular",
    marginBottom: 20,
  },
  autor: {
    fontFamily: "CedarvilleCursive_400Regular",
    width: "100%",
    color: "black",
    textAlign: "center",
    fontSize: 20,
  },
  LinhaPreta: {
    width: "100%",
    height: 2,
    backgroundColor: "black",
  },
  preco: {
    width: "100%",
    color: "black",
    textAlign: "center",
    fontSize: 25,
    fontFamily: "CedarvilleCursive_400Regular",
  },
  CaixaDeDescricao: {
    position: "relative",
    width: "90%",
    height: "20%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    top: "45%",
    padding: "4%",
    borderRadius: 5,
  },
  descricao: {
    width: "100%",
    height: "100%",
    color: "white",
    fontSize: 15,
    textAlign: "justify",
  },
  SecaoDeBotoes: {
    position: "absolute",
    bottom: "15%",
    width: "90%",
    height: "8%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  BotaoDeVoltar: {
    position: "absolute",
    width: "18%",
    height: "100%",
    left: "0%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    elevation: 4,
  },
  BotaoDeComprar: {
    position: "relative",
    width: "60%",
    height: "100%",
    backgroundColor: "green",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    marginBottom: "5%",
  },
  posicionarElementosNoBotaoDeComprar: {
    position: "absolute",
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  TextoDentroDoBotaoDecomprar: {
    width: "100%",
    fontSize: 25,
    color: "white",
    textAlign: "center",
    fontWeight: "bold",
    marginLeft: "5%",
  },
  BotaoHome: {
    position: "absolute",
    width: "18%",
    height: "100%",
    right: "0%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    elevation: 4,
  },
  ImagemDoBotao: {
    position: "absolute",
    width: 30,
    height: 30,
    elevation: 4,
  },
});
export default TelaDoLivroStyles;
