import { StyleSheet } from "react-native";
const VerificarStyles = StyleSheet.create({
  body: {
    position: "absolute",
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
  },
  Modal: {
    width: "80%",
    height: "40%",
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    overflow: "hidden",
  },
  Titulo: {
    position: "absolute",
    color: "black",
    width: "100%",
    textAlign: "center",
    fontSize: 25,
  },
  BotaoDeVoltar: {
    position: "absolute",
    width: 55,
    height: 55,
    top: "-3%",
    left: "-3%",
    borderBottomRightRadius: 15,
    backgroundColor: "black",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  input: {
    position: "absolute",
    top: "25%",
    width: "80%",
    height: 40,
    borderBottomWidth: 2,
    borderBottomColor: "black",
    color: "black",
    paddingTop: 20,
  },
  BotaoDeVerificar: {
    position: "absolute",
    bottom: "15%",
    width: 200,
    height: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "black",
    borderWidth: 2,
    borderRadius: 20,
  },
});
export default VerificarStyles;
